apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: spike-dcs-mtls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
data:
  nginx.conf: |
        user  nginx;
        worker_processes  1;

        error_log  /var/log/nginx/error.log warn;
        pid        /var/run/nginx.pid;


        events {
          worker_connections  1024;
        }


        http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
          '$status $body_bytes_sent "$http_referer" '
          '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;

          keepalive_timeout  65;

          server {
            listen       80;
            server_name  localhost;

            location / {
              add_header lol $http_lol;
              add_header X-Forwarded-Client-Cert $http_x_forwarded_client_cert;
              return 200;
            }
          }
        }
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  hosts:
  - "lol.london.sandbox.govsvc.uk"
  gateways:
  - gsp-gsp-cluster.gsp-system
  http:
  - route:
    - destination:
        host: spike-dcs-mtls
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
