apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.2
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: spike-dcs-mtls
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
data:
  nginx.conf: |
        user  nginx;
        worker_processes  1;

        error_log  /var/log/nginx/error.log warn;
        pid        /var/run/nginx.pid;


        events {
          worker_connections  1024;
        }


        http {
          include       /etc/nginx/mime.types;
          default_type  application/octet-stream;

          log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
          '$status $body_bytes_sent "$http_referer" '
          '"$http_user_agent" "$http_x_forwarded_for"';

          access_log  /var/log/nginx/access.log  main;

          sendfile        on;

          keepalive_timeout  65;

          server {
            listen       80;
            server_name  localhost;

            location / {
              add_header lol $http_lol;
              add_header X-Forwarded-Client-Cert $http_x_forwarded_client_cert;
              return 200;
            }
          }
        }
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  hosts:
  - "lol.london.sandbox.govsvc.uk"
  gateways:
  - spike-dcs-mtls
  http:
  - route:
    - destination:
        host: spike-dcs-mtls.spike-dcs-mtls.svc.cluster.local
        port:
          number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: spike-dcs-mtls
  namespace: spike-dcs-mtls
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: MUTUAL
      serverCertificate: /etc/istio/ingressgateway-certs/tls.crt
      privateKey: /etc/istio/ingressgateway-certs/tls.key
      caCertificates: /etc/istio/ingressgateway-ca-certs/ca-chain.cert.pem
    hosts:
    - "lol.london.sandbox.govsvc.uk"
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-ingressgateway-certs
  namespace: istio-system
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZiakNDQTFhZ0F3SUJBZ0lERUFJU01BMEdDU3FHU0liM0RRRUJDd1VBTUZNeEN6QUpCZ05WQkFZVEFsVlQKTVE4d0RRWURWUVFJREFaRVpXNXBZV3d4RERBS0JnTlZCQW9NQTBScGN6RWxNQ01HQTFVRUF3d2NiRzlzTG14dgpibVJ2Ymk1ellXNWtZbTk0TG1kdmRuTjJZeTUxYXpBZUZ3MHhPVEEzTWpZd09USTBNREJhRncweU1EQTRNRFF3Ck9USTBNREJhTUdreEN6QUpCZ05WQkFZVEFsVlRNUTh3RFFZRFZRUUlEQVpFWlc1cFlXd3hGREFTQmdOVkJBY00KQzFOd2NtbHVaMlpwWld4a01Rd3dDZ1lEVlFRS0RBTkVhWE14SlRBakJnTlZCQU1NSEd4dmJDNXNiMjVrYjI0dQpjMkZ1WkdKdmVDNW5iM1p6ZG1NdWRXc3dnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCCkFRRGtWVjVmT2luR054NFk4dGhFc2VCNnU1UmJEd2RKUnVFMWpaUEtkWnBDbmJ5cmNHTnVQRjdmcS9BK0U4L3AKSmxoa0NPZmNUNWVrN0pINDZxaTc4bmpCL1p1YUI4aFpsV29aN1U3c0FMODZ3YU9mWEM1aW55bjVIUmlJZnBzZgpRZms3MVBTdnVPKzkwbmVweTlWU3k0aGU0RWRoWTNZejdKTGhISzhlWjUzRzBQOWc2SUdiRE1FTFk0SEdJR3BSCnNvdkNMZm5UYXQ3OWFxRHkwRE4vV2Fob1RWbW0rMXgxWU1NZXFFWmIxSENXa3pPbk0vM1BrdnNIOE0xdENpTEkKaUhFRll2a013UEN6cFJWbmk5OHdEbXE3dWpERDJNdUdWenJqdkxabHF5Z2MyNXI3bVJTYUVXNU4xcU9tVGlpKwpQemVHRjRvSEd0SkcxUEk3TXN3bmxCWjVBZ01CQUFHamdnRXpNSUlCTHpBSkJnTlZIUk1FQWpBQU1CRUdDV0NHClNBR0crRUlCQVFRRUF3SUdRREF6QmdsZ2hrZ0JodmhDQVEwRUpoWWtUM0JsYmxOVFRDQkhaVzVsY21GMFpXUWcKVTJWeWRtVnlJRU5sY25ScFptbGpZWFJsTUIwR0ExVWREZ1FXQkJTdGJjMGI5UThCeGx6aElnSVh1RUlmUU8xNwo4ekNCbFFZRFZSMGpCSUdOTUlHS2dCVDdUNHB6YTd5N0tpK05jT0JoeStqMnFJSWpLS0Z0cEdzd2FURUxNQWtHCkExVUVCaE1DVlZNeER6QU5CZ05WQkFnTUJrUmxibWxoYkRFVU1CSUdBMVVFQnd3TFUzQnlhVzVuWm1sbGJHUXgKRERBS0JnTlZCQW9NQTBScGN6RWxNQ01HQTFVRUF3d2NiRzlzTG14dmJtUnZiaTV6WVc1a1ltOTRMbWR2ZG5OMgpZeTUxYTRJREVBSVNNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBVEFOCkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWxMWFpuU2VqN2R1RG0rdkt1TjlMWVFtSjArNXYrMi9kMndJZ1lBQnQKR0hBQURkbDN2U25VODc4QnJEZ05jMjhENFBTSUVuVkV4MXNSUTh3VTdNdnVuTXpGd1ZtNnkzU3ZXVW9oclJIdgpYRTR0VFV3NkZTaS9mYThRanZiWktqSEJWQmJEMlpoK3gyc3Bja09WbXB0OHdUSlJNbkY0OG9PWFNNUXAzVVBMCng0eDRFV0tHUlM3Tzk4MFNBbjFrVzdDK29vUzFLKzJIZkp2Tjh0TDZwY0F4ZDlha1FpcWhzOUJwR1ZrUStPdXUKNzlOQ2t2WjdOYzcyVFdxR1ZRNW5rTDZTbFpEWTVUVTBiRjRSVWp1RVpvUjdkWmR3Ni9lY2s0TitNTEczUnBZdApHYXBYVElZb3k5UWdHN2Z6UGRLUTBNU20ycWdVS2xzdG9OZHcvUk1PL3hCYnVSN2lSck1lMVhUYW02elR5TlJ3CkM2bDNOUkhPYjVVZFJjM3dycmQwUzJGZmR0YWdKMlBCcW9hdE5IQlRoUWpzNE9CTDBlM0hUa1k4VE1DeEc3TzMKb3E4Q05GaytlMy8xUWxFQnhVa1dUbEtGRUNtT1hTWEZYYUh1bC9aaXU5d3pCeDU3VEJOUDJYNXM0OXovdTlOSwpDUVF3VWFHN0thakVVeTBjU2VraFNNakRlRDJMM2hYQlpRNVpXM21CYlRhdk15MjRyQklRTkJzeXFpUmdSclFpCndORllyUy9Jb2xaOEJvSUJySGFNdFM1a1M5TFF3NE14L0NSWGZMbnoyVEZ6NStFcjBLdGhPcFFnWVBMdnZrZmsKV3ZOaFExN0lqSUhvRHZsV2RDeWlMVlBScEFhZnFKTDV4Z2lTcENhczVMRnJXekVBUkZEeXpIbnJtei8zWDB3Vwo0S0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBNUZWZVh6b3B4amNlR1BMWVJMSGdlcnVVV3c4SFNVYmhOWTJUeW5XYVFwMjhxM0JqCmJqeGUzNnZ3UGhQUDZTWllaQWpuM0UrWHBPeVIrT3FvdS9KNHdmMmJtZ2ZJV1pWcUdlMU83QUMvT3NHam4xd3UKWXA4cCtSMFlpSDZiSDBINU85VDByN2p2dmRKM3FjdlZVc3VJWHVCSFlXTjJNK3lTNFJ5dkhtZWR4dEQvWU9pQgptd3pCQzJPQnhpQnFVYktMd2kzNTAycmUvV3FnOHRBemYxbW9hRTFacHZ0Y2RXRERIcWhHVzlSd2xwTXpwelA5Cno1TDdCL0ROYlFvaXlJaHhCV0w1RE1Ed3M2VVZaNHZmTUE1cXU3b3d3OWpMaGxjNjQ3eTJaYXNvSE51YSs1a1UKbWhGdVRkYWpwazRvdmo4M2hoZUtCeHJTUnRUeU96TE1KNVFXZVFJREFRQUJBb0lCQUdseXEyU2EvZFBXZklYVgpFTitZcml6QUdDRjliVVgvLzkyMWhuMUhsbmdSVktKd0F0dFQ4aFNsMlFzeUp5QnJYd0xEd2lCU2Vadm16UHNCCmsrOUlhVkJkaU5DM3EyVUR4YjQzZyswbDR5cUZac1VmMHlRa2tVUEVsaUhqSmt4bk1XemFTaTRrNEVMdndlZWUKaE9QNXJ2N3g0TVV2STlXUytib1FmeWN4ZndIamY0NU1pc2d3bDVkUGZTZU9mcUEwTWNTbnBCUHRIaWpvMTFkMgpKelVOMlJEZ0dabEszQTNacmxlNUJweStLRzhXd2JncnJiMFhDdlJJcWRyUlp3M0MxTkNlRG5aY0ZLanFLN1FUCktud0k4aWdYczhKMllyRktCTUhnN05HZWtKazNBV01GUldQUzN2NzdDV1FsWUtsZnp2eGlsbjZQYzJ2YUwyeGQKVDJVMm55a0NnWUVBL3RVcms1QzQyeXlWYm90aGVPTWRrK1luem5iZXY2elc0MVFpL1VscFVMekErMUV6aENSVwpnSVJLUElaQUhMNG5iNnRlUVplUFowNW5kTG9lUjdYRFBOaU05NlBETFhIelJWa2VtcXZEeVpkVlI5RTRRR2dkCkhkcmxaZnU4M1gxazVEc0g4NGpmcjJQaloxRWdpREFEZncwdTUxK0l2SldtT01MbHMvQzBFcE1DZ1lFQTVXRWYKdzhzUWpmU0lwU2tuenRrdkQvbTN4WFdLUXNGRWUrVmdLdVp3UDVkeEFwNDJ4ZXdSRTNIQmVNYWFCTHVFYUFSUQp0QXFqQ0lHWXA2ZEZvalRnRkZ3TEEyTEhPMDVLWEs2OUlHTzIvdnl4STBJVllJcWowMGRaMGdJQUFGeE8wYnZ0CkdnVkVEMENkTFd0TWVmSUZVRU9TOWo4KytTamF1UERjTFlaaUhrTUNnWUFRUzlPSWtVV3hCbTNiN3QvaDJpeEgKQy8zWnJ6SlpjWlVnWG40S1VvcUFsa0dGRU5GSmp3VlZIS0NldERzZlcyMnNMM3BNbVlPYktLRm5Eb3ZuTEJGNwpMNkg4S0NYUUh5eGViKytNRnBYanEyRFJ3ZWhsL2dKMnFVdm9OS3dFUWdPVXNNMjJYamRud095RzYrSTNzMUpWCjZxTG9PdXpFbXBGUnFlMEVqODBFTHdLQmdRREovUWdLMDFQRm5iT0N0VVlmeVhLKy82akxraURwZmVWL3NOSkoKbE5qOXRxOUduZW9meWl5VFVkWU1NOTlIRVpXY1AwaU44dHYwVHFNTjU2ZlRHZnJGRXZTRHk4VWp2V0tRVVRPcwpSUUxOY2RuTzhZOS9qemFLZzhkZHZuTWYzaWx1V2EyRi8yTWFoMHloeFYzMytKNmpPbzQ4bUI4dEs4UEhuaHBWCllJUWdud0tCZ1FES3B1Mk1QcXVHSS82QnRsTGNvUy8wcjVLdlFxL1V4djl0NFZKSFNreHQrdzYwT2pWZkpDeWsKaXN0bTRhVVVjbWNDZUNsMkIwTzl5TkRudCtRNjRSblNJZnhNK2RtK2FtK0RNaHdKd3R6WXV4UytlWW9OMmlZRQp3V0UyZ3hiaHRYQzYyaXg3YUsrSEJqdXMzNFNCT3h3UTl3Q3JzNTU5RENJUkxZYUwzY1VxZkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Secret
metadata:
  name: istio-ingressgateway-ca-certs
  namespace: istio-system
type: Opaque
data:
  ca-chain.cert.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZuekNDQTRlZ0F3SUJBZ0lERUFJU01BMEdDU3FHU0liM0RRRUJDd1VBTUdreEN6QUpCZ05WQkFZVEFsVlQKTVE4d0RRWURWUVFJREFaRVpXNXBZV3d4RkRBU0JnTlZCQWNNQzFOd2NtbHVaMlpwWld4a01Rd3dDZ1lEVlFRSwpEQU5FYVhNeEpUQWpCZ05WQkFNTUhHeHZiQzVzYjI1a2IyNHVjMkZ1WkdKdmVDNW5iM1p6ZG1NdWRXc3dIaGNOCk1Ua3dOekkyTURreU16UTFXaGNOTWprd056SXpNRGt5TXpRMVdqQlRNUXN3Q1FZRFZRUUdFd0pWVXpFUE1BMEcKQTFVRUNBd0dSR1Z1YVdGc01Rd3dDZ1lEVlFRS0RBTkVhWE14SlRBakJnTlZCQU1NSEd4dmJDNXNiMjVrYjI0dQpjMkZ1WkdKdmVDNW5iM1p6ZG1NdWRXc3dnZ0lpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElDRHdBd2dnSUtBb0lDCkFRREVaeU0wUGl4dUdKMEQ2WHZNKytmRXFYeXRCajZsUkEvSExLdlVhejdGam1QbklMM1NFMmdMbDQrZXlMOXUKWlUxbXhpRWJhK21Tb3Z3eG5hbTlEWTZ6dUpRazc4M2diVlVwZ0RkTUJxSEx2aDBFcVBnSHgwVytpL0owcnd6aQphcktaeEpvcGh1UHBnenFrRTlDWXRQQk9xZnRFZmFtOXlZbmFxR1FHZXpHaW54c2Y4RFZhV3gyWWpVZGYvYkhWCkRJUGxXNU44V3oyako1RHpVZmt5VTZEWmdWelJVUG9RT05yNXpTNGZxR1poSHpsS0pXc1dHMkhDWVFuK3I3bksKeUhMOGJkK0JWRUV6N1lUTzlvNytJN3NLUGpsOCs1UVBkclhiWEFiQnhHVlBYSkpKQklLZnBNcnEwUnJwajVDVApXdld0cUhGNG1UMHZqOHE0azVNM2hUY2hHd2QxL0MvQzRDc3lVRlBoYjIwTHFCWTF5R0JhUDNEeDVvUElZbW15CkluRmMxdVZWMGkxTnFGa3d5L0w5QUloT2pBeTJQMTBZaEp4ajc5bVJGZ0U0YjMvYlpjZFE1UFJnbGRsQzYvNmIKSTF6SDl1MkFSby96Vk1KTXB3VDljRkFMa3NNby95WWFZUzY3ckt2ZndRYkF5SmgzeU9yeTc0MCtwemZHS09JUQp2ZmczdVFNcE9uc2RRUWgzblhpS1F6WVhFMnZkSFl3eHdQRTM0dHlMSUl0Y1p1S0Zzb3ovRldnUDgwOE5pejZFCmU4ZzY0UCtGbXdRdWk5SzZUS2JXalc1TGZqN0FQUU5aRktVZlc1Qi9BWStVWm1vaUZmYi81bXFQb2Jib0NJZE0KQkhoNXR2d1RwSlR6aUx0TVM1c3ord2pLR0tmZVhYL1F0dThMK2pybit1cHpLd0lEQVFBQm8yWXdaREFkQmdOVgpIUTRFRmdRVSswK0tjMnU4dXlvdmpYRGdZY3ZvOXFpQ0l5Z3dId1lEVlIwakJCZ3dGb0FVWkl0MmYxUi9vZ1Q0Cmw2YXVJTmJsN296dS85NHdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUJBREFPQmdOVkhROEJBZjhFQkFNQ0FZWXcKRFFZSktvWklodmNOQVFFTEJRQURnZ0lCQUUvQXZoWXhWMU9Mc1dqb0M3Um9PTDN3VHVRRDE2cDJZSHpvcFhIVApMNG9DNEdSZTdvNStWVVprL0tlSXZjbVJjaXk4ejVnbmNEY29ON0ZnT3Z5eVpqL2lydXFiTkJWOGRZczFZeWR0CjViL3dpcTJzSTZ2K0dXU2hhcjRVdlg0MXFxNDk1ZkFTWFBtQlltNnlwcE1HWUdSTzBYamdnRjRyTzhSejhPWUcKdFRJNkkweUV5VUtIbitnNGFrL3FKd3FMZHR2VlFwVE92V0pkQU1qYUVPcFJyQ2crNjBOLzY2QzhEeVRXWVorOQpQU0ROaVkxcHVnVUwvOHFMOWVzQ3M3UEtneFlvTDhDMkpFbTF0Mi9selg1OGdqWmthcTFQNXQ5bGJzUDVLZFJQCk42NXBEdFkxZUdudjJGSEY1NVpTZFBWRnMxRmJxeDJDaUtPYms0eWtrbTBGUU82eGlhRGJPajRIS1J0djI3aXUKa0RSMWxwUlNGM2lvbVFaUnRqNERRWWo0RXBWTWNwWjZGdCtHZ0NNVHAzUHo3L3hqd3VFVllsN09iWVIyVklyZgpuekJhU2ttRkFvWmVmVU8rSGZOcUdkUlppS0VZM2JPODdtV3A5SlVERjUwZjdvK2tEcHF6UWsxdzJ0SXMyOUZXCmZ5b01xc0VBbTFwMEwxTzByRWhwbktucjBpMHBxcGJ6TFQrVzViaHFIZnhLcU5jMC9KdUFVSUdWWEpuNjAwdDQKb0dISnFmWkN6c3FXWlV1VFpQTVFVMG5NYmRzMHk3bGxMZW51VFo3SitsUWNhMmlIaDdsS0hkL056a1I4elZIYgpQQ0pMS3E5K2tFNitzT2s1YVRScVBRMHpNaXUrTGxWczJLcmFKMlRKb1lqek5wQ0FxY3A2VGtxN0hML0lkU3ZuCnorSjUKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRnVEQ0NBNkNnQXdJQkFnSUpBUDJ2Syt0bEh3cTVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1Ha3hDekFKQmdOVgpCQVlUQWxWVE1ROHdEUVlEVlFRSURBWkVaVzVwWVd3eEZEQVNCZ05WQkFjTUMxTndjbWx1WjJacFpXeGtNUXd3CkNnWURWUVFLREFORWFYTXhKVEFqQmdOVkJBTU1IR3h2YkM1c2IyNWtiMjR1YzJGdVpHSnZlQzVuYjNaemRtTXUKZFdzd0hoY05NVGt3TnpJMk1Ea3lNek0zV2hjTk16a3dOekl4TURreU16TTNXakJwTVFzd0NRWURWUVFHRXdKVgpVekVQTUEwR0ExVUVDQXdHUkdWdWFXRnNNUlF3RWdZRFZRUUhEQXRUY0hKcGJtZG1hV1ZzWkRFTU1Bb0dBMVVFCkNnd0RSR2x6TVNVd0l3WURWUVFEREJ4c2Iyd3ViRzl1Wkc5dUxuTmhibVJpYjNndVoyOTJjM1pqTG5Wck1JSUMKSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQWc4QU1JSUNDZ0tDQWdFQTVPUXY4aHJnVkZXbXpRNVZpUzMzNSt2TwpzMElMazFEc2g0bTk1Y3JQU3FmRFdIeUtLbTF2T1JaZnRGU05qMS9QTEpKbDVTUGdEczBQY0YxZEJNNnVnNjdNCkZUdDQvQjJXUmFCeFV4VmhJSTVRWDUyQ1J0ZDkrcW1ydkxyKys4emxSSi9rR1l6UE0rN3ZETTltSDdLUk5Xd3QKa08wVTZ2TWxMRHJGbzl0ZkRUcS9Ic2lXQ1pqOTdrVVM3bDhoL09HMnROOWd5azFBb3c0UjBxSWpab242dnF1WQp2N2RycFF5Q2NOc3BITEpDemJXZkJnMUNvcVp2bVhEa2FCaHI4UTIvSHh3ZFRxaXd0TGh0V1kzcDM4dlFWakkzCkJHU1V3cnpBWEdrR2s0ZFU0S09paVVkTXc5OWZDVVNEV2NDT0ZiczVTYWJNcjJEdm8wUHdkTnlCVlhKYVZkY1gKd25TOVd2ZW00cHkxbEZoWC84ZG84dTI1WXd0Y2lPeGhBOUFtcWc0NzZZa2I5SDE5cnhaNDJSRVluOWc1bTBzUQpyRm5XNDhnejhhY0h3dFdqdzlWQWFVVUhKMHdzazlRRlQ4d3lBQkc2KzQzeThQT2dIQWxONUdGN2RwQjdCM1N1CkEvSlAzK25tb0ZIMDR6SkZRaTdMNGczK3g4ODdMRFpmWFpyZDB3UFhSK1BwaXJta0pjUGdzanhIVmlnc0xCcEcKRmV4aXUyb2FmS0VDZExJUTc1NGw0Tm9xTWFkKzcwSkNOa3RvSjNFbjJkZTNtTEFYR0RIY2N2NE9OR1hURVRhSQpFNCszblE1VEdESjBRZ3J0WUhTQkVicmMrMy9GdmtkOWRyRFZmOTg3ZVBpQUR3WjZtUG56NmUzajFLOVUwTGJBClZiRzZLR29iZm1pdlFZdUNGaThDQXdFQUFhTmpNR0V3SFFZRFZSME9CQllFRkdTTGRuOVVmNklFK0plbXJpRFcKNWU2TTd2L2VNQjhHQTFVZEl3UVlNQmFBRkdTTGRuOVVmNklFK0plbXJpRFc1ZTZNN3YvZU1BOEdBMVVkRXdFQgovd1FGTUFNQkFmOHdEZ1lEVlIwUEFRSC9CQVFEQWdHR01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQy95VUxtCnBFNnhwT2xKTnFQOTNESnJDQ2J1V0c1dzB6MEVaY2ttRVlCTi9oSTBOZHY3TjJtMFRWWXRPQ01CZGYxSTgyTkQKVUJXaDRUVmo1azZLNjZhVmo4ZTNpd1NuV1Ztak5CTTJGMzYzZGVqbmpIcVJuYlF5VEJMMVNrclpxTW03TW9oNgpkaHh4TTE0UGFBRyt4YUFuVU4yS1ROcHZqTlh2eG04bnFJeGRxNXRNQWVHVXJjalBTRHhMWmJTaldwOUwrSlRDCkpOS3N1MnBFU2cxdC9aMnROcEZEdE84WnM5U0EzaXcvbUgvR0kwdjUzcHBUellTVFdISzB2N1VqV1M1OGkzNHoKWlE3UjJIOFZjZnJIckFKZitFUCtWT3pjWXMrVjVjOGk5Wjl6UnFRS1p1SW1ZdnpoY1NwVEMvc1pHREhVWmdNdApZQjhiNUxxTHp6YjEydVpWRHpSM0RuWnRoVWV3WEVhcmNsU3VOMEUrUDBiWjlZQU9QdENZYkdSRWVjWEo3UmR3CnNuN1BQUkZCVkI0cFM5K0wydE5ybERsamJvaGVPMDhzLzB5Vkd5Wm50Y1dMMU9CSVBqaG9pUkZDamJMTDlzYm8KeThWakV0K3lhRlJXWnJYbkF0MDByWVplRWZ0bjVtb1MvNktLZG40bVZnOHpWOWQzNFg4cW96K0F1QlkzVldrUgpqOXN6cG5QZDcvd2tPRVdGYTZmUHc0VkJjVlFiSXI4ekR6N0dSc3pVek1PM2N1WVFHMEJNQkExV3BLalAxRmc4CnlwR3FGUDd6bnFmVS9TMGZGN2tLdnZDNGJ6YWhJN2RDWG9KejdBYzZ6OVJtSFh2RVdHS0VoeTl6VC9BdHdsdjYKL2Vnc2tnTXdvejc0a3lkdElQSnN4SzVZTURKdjFVMnV2U29oS1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
