language: bash
sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - shellcheck components/concourse-harbor-resource/assets/**/*

matrix:
  fast_finish: true
