{{- range .Values.namespaces }}
{{- range .resources }}
---
{{ tpl (toYaml .) $ }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .name }}
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log", "services/proxy", "namespaces"]
  verbs: ["get", "watch", "list", "describe"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-pod-reader
  namespace: {{ .name }}
subjects:
- kind: Group
  name: {{ .name }}-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
