---
apiVersion: v1
kind: Namespace
metadata:
  name: gsp-canary
  labels:
    namespace: gsp-canary
    istio-injection: disabled
  annotations:
    iam.amazonaws.com/permitted: "^{{ .Values.global.roles.canary }}$"
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: canary
spec:
  releaseName: canary
  chart:
    git: {{ .Values.global.canary.repository }}
    ref: "master"
    path: "charts/gsp-canary"
    verificationKeys: {{ .Values.global.canary.verificationKeys }}
  values:
    annotations:
      iam.amazonaws.com/role: {{ .Values.global.roles.canary }}
    updater:
      helmChartRepoUrl: {{ .Values.global.canary.repository }}
