{{- $clusterName := .Values.global.cluster.name }}
{{- range .Values.namespaces }}
{{- $ns := . }}
{{- range .resources }}
---
{{ tpl (toYaml .) $ }}
{{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .name }}
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log", "services/proxy", "namespaces"]
  verbs: ["get", "watch", "list", "describe"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-pod-reader
  namespace: {{ .name }}
subjects:
- kind: Group
  name: {{ .name }}-dev
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: concourse.k8s.io/v1beta1
kind: Team
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: {{ trimPrefix (printf "%s-" $clusterName) .name }}
spec:
  roles:
  - name: owner
    local:
      users: ["pipeline-operator"]
  - name: pipeline-operator
    local:
      users:
      {{- range $.Values.users }}
        {{- $user := . }}
        {{- range .roles }}
          {{- if and (hasPrefix $clusterName .) (hasSuffix "-sre" .) }}
        - {{ $user.github }}
          {{- else if and (hasPrefix $clusterName .) (hasSuffix "-admin" .) }}
        - {{ $user.github }}
          {{- else if and (hasPrefix $ns.name .) (hasSuffix "-dev" .) }}
        - {{ $user.github }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}
