platform: linux
image_resource:
image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: "1.5.0"
inputs:
- name: release
outputs:
- name: version
run:
  path: /bin/bash
  args:
  - -eu
  - -c
  - |
    echo "bumping release number..."
    CURRENT_TAG=$(cat release/tag)
    sed  "s/${SRC_TAG_PREFIX}//" <<< "${CURRENT_TAG}" | awk -F. '/[0-9]+\./{$NF++;print}' OFS=. | sed "s/^/${DEST_TAG_PREFIX}/" > version/tag
    NEW_TAG=$(cat version/tag)
    echo "${NEW_TAG}" > version/name
    cat version/name
