platform: linux
image_resource:
image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: "1.5.0"
params:
  NAME_PREFIX: ""
inputs:
- name: release
outputs:
- name: version
run:
  path: /bin/bash
  args:
  - -eu
  - -c
  - |
    echo "bumping release number..."
    CURRENT_TAG=$(cat release/tag)
    awk -F. '/[0-9]+\./{$NF++;print}' OFS=. <<< "${CURRENT_TAG}" > version/tag
    NEW_TAG=$(cat version/tag)
    echo "${NAME_PREFIX}${NEW_TAG}" > version/name
    cat version/name
