platform: linux
image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: "1.5.0"
params:
  ACCOUNT_NAME: gds
  CLUSTER_PUBLIC_KEY:
inputs:
- name: users
outputs:
- name: trusted-contributors
run:
  path: /bin/bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    echo "preparing keyring to verify user release..."
    echo "${CLUSTER_PUBLIC_KEY}" > key
    gpg --import key
    gpg --verify "users/${ACCOUNT_NAME}-trusted-developers.yaml.asc"
    echo "generating list of pipeline approvers..."
    trusted_approvers="trusted-contributors/github.vars.yaml"
    echo -n "config-approvers: " > "${trusted_approvers}"
    yq '.[]' "users/${ACCOUNT_NAME}-trusted-developers.yaml" \
      | jq -c -s "[.[] | .github] | unique | sort" \
      >> "${trusted_approvers}"
    cat "${trusted_approvers}"
