platform: linux
image_resource:
image_resource:
  type: docker-image
  source:
    repository: govsvc/task-toolbox
    tag: "1.5.0"
params:
  ACCOUNT_NAME: gds
inputs:
- name: users
outputs:
- name: trusted-contributors
run:
  path: /bin/bash
  args:
  - -euo
  - pipefail
  - -c
  - |
    trusted_approvers="trusted-contributors/github.vars.yaml"
    trusted_keys="trusted-contributors/keys.vars.yaml"
    echo "generating list of pipeline approvers..."
    echo -n "github-approvers: " > "${trusted_approvers}"
    yq '.[]' "users/${ACCOUNT_NAME}-trusted-developers.yaml" \
      | jq -c -s "[.[] | .github] | unique | sort" \
      >> "${trusted_approvers}"
    cat "${trusted_approvers}"
    echo "generating list of all trusted signing keys"
    echo "trusted-developer-keys=$(yq -c . users/gds-trusted-developers-keys.yaml)" \
      > "${trusted_keys}"
    cat "${trusted_keys}"
