
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: principals.access.govsvc.uk
spec:
  group: access.govsvc.uk
  names:
    kind: Principal
    plural: principals
  scope: ""
  validation:
    openAPIV3Schema:
      description: Principal is the Schema for the Principal API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        status:
          description: PrincipalStatus defines the observed state of Principal
          properties:
            events:
              description: Events will hold more in-depth details of the current state
                of the instance.
              items:
                description: Event is a single action taken against the resource at
                  any given time.
                properties:
                  reason:
                    description: Reason for the current status of the instance.
                    type: string
                  status:
                    description: Status of the currently running instance.
                    type: string
                  time:
                    description: Time of the event cast.
                    format: date-time
                    type: string
                required:
                - status
                - time
                type: object
              type: array
            id:
              description: ID of an instance for a reference.
              type: string
            name:
              description: Name of the IAM Principal
              type: string
            reason:
              description: Reason for the current status of the instance.
              type: string
            status:
              description: Status of the currently running instance.
              type: string
          required:
          - id
          - name
          - status
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: postgres.database.govsvc.uk
spec:
  group: database.govsvc.uk
  names:
    kind: Postgres
    plural: postgres
  scope: ""
  validation:
    openAPIV3Schema:
      description: Postgres is the Schema for the postgres API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PostgresSpec defines the desired state of Postgres
          properties:
            aws:
              description: AWS specific subsection of the resource.
              properties:
                instanceType:
                  description: InstanceType essentially defines the amount of memory
                    and cpus on the database.
                  type: string
              type: object
            secret:
              description: Secret name to be used for storing relevant instance secrets
                for further use.
              type: string
          type: object
        status:
          description: PostgresStatus defines the observed state of Postgres
          properties:
            events:
              description: Events will hold more in-depth details of the current state
                of the instance.
              items:
                description: Event is a single action taken against the resource at
                  any given time.
                properties:
                  reason:
                    description: Reason for the current status of the instance.
                    type: string
                  status:
                    description: Status of the currently running instance.
                    type: string
                  time:
                    description: Time of the event cast.
                    format: date-time
                    type: string
                required:
                - status
                - time
                type: object
              type: array
            id:
              description: ID of an instance for a reference.
              type: string
            reason:
              description: Reason for the current status of the instance.
              type: string
            status:
              description: Status of the currently running instance.
              type: string
          required:
          - id
          - status
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: sqs.queue.govsvc.uk
spec:
  group: queue.govsvc.uk
  names:
    kind: SQS
    plural: sqs
  scope: ""
  validation:
    openAPIV3Schema:
      description: SQS is the Schema for the SQS API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SQSSpec defines the desired state of SQS
          properties:
            aws:
              description: AWS specific subsection of the resource.
              type: object
            secret:
              description: Secret name to be used for storing relevant instance secrets
                for further use.
              type: string
          type: object
        status:
          description: SQSStatus defines the observed state of SQS
          properties:
            events:
              description: Events will hold more in-depth details of the current state
                of the instance.
              items:
                description: Event is a single action taken against the resource at
                  any given time.
                properties:
                  reason:
                    description: Reason for the current status of the instance.
                    type: string
                  status:
                    description: Status of the currently running instance.
                    type: string
                  time:
                    description: Time of the event cast.
                    format: date-time
                    type: string
                required:
                - status
                - time
                type: object
              type: array
            id:
              description: ID of an instance for a reference.
              type: string
            reason:
              description: Reason for the current status of the instance.
              type: string
            status:
              description: Status of the currently running instance.
              type: string
          required:
          - id
          - status
          type: object
      type: object
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
