
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-service-operator-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.gsp.k8s.io
  - queue.gsp.k8s.io
  resources:
  - postgres
  - sqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - database.gsp.k8s.io
  - queue.gsp.k8s.io
  resources:
  - postgres/status
  - sqs/status
  verbs:
  - get
  - patch
  - update
