{{- if .Values.global.runningOnAws }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  labels:
    control-plane: {{ .Release.Name }}-service-operator
  name: {{ .Release.Name }}-service-operator-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: {{ .Release.Name }}-service-operator
{{ end }}
