---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-sentry
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  hosts:
  - "sentry.{{ .Values.global.cluster.domain }}"
  gateways:
  - {{ include "gsp-cluster.fullname" . }}-ingress
  http:
  - route:
    - destination:
        host: {{ template "sentry.fullname" . }}
        port:
          number: 9000
