dependencies:
  - name: istio
    version: 1.3.5
    repository: https://storage.googleapis.com/istio-release/releases/1.3.5/charts/
  - name: istio-init
    version: 1.3.5
    repository: https://storage.googleapis.com/istio-release/releases/1.3.5/charts/
  - name: istio-cni
    version: 1.3.5
    repository: https://storage.googleapis.com/istio-release/releases/1.3.5/charts/
