dependencies:
  - name: istio
    version: 1.2.7
    repository: https://storage.googleapis.com/istio-release/releases/1.2.7/charts/
  - name: istio-init
    version: 1.2.7
    repository: https://storage.googleapis.com/istio-release/releases/1.2.7/charts/
  - name: istio-cni
    version: 0.1.0
    repository: https://storage.googleapis.com/istio-release/releases/1.2.7/charts/
