---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ci-deploy-key
  namespace: {{ .Values.namespace | quote }}
data:
  private_key: {{ .Values.global.ci.privateKey | b64enc | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ci-deploy-key
  namespace: {{ .Values.namespace | quote }}
data:
  public_key: {{ .Values.global.ci.publicKey | quote }}
