kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "services", "pods/log", "services/proxy", "namespaces"]
  verbs: ["get", "watch", "list", "describe"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
