apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequireImageDigest
metadata:
  name: digests-on-internal-registry
spec:
  enforcementAction: dryrun
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    registry: "registry.{{ .Values.global.cluster.domain }}"
