---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gsp-prometheus
  namespace: gsp-system
  labels:
    chart: gsp-cluster
spec:
  hosts:
  - "prometheus.local.govsandbox.uk"
  gateways:
  - "gsp-gsp-cluster.gsp-system"
  http:
  - route:
    - destination:
        host: gsp-prometheus-operator-prometheus
        port:
          number: 9090
