---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gsp-concourse
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    # It is difficult to find, therefore:
    # https://concourse-ci.org/managing-teams.html#setting-roles
    roles:
    - name: owner
      local:
        users: ["pipeline-operator"]
    - name: pipeline-operator
      github:
        teams: {{ .Values.concourseMainTeamGithubTeams }}
