{{- range $egress := .Values.egressSafelist }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: {{ $.Release.Name }}-{{ $egress.name }}
  namespace: {{ $.Release.Namespace }}
spec:
{{- $egress.service | toYaml | nindent 2 }}
{{- end }}
