---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-grafana-datasource'
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasource.yaml: |-
{{ .Files.Get "datasources/cloudwatch.yaml" | indent 4 }}
