---
apiVersion: v1
kind: Secret
metadata:
  name: grafana
  namespace: gsp-system
data:
  GF_AUTH_GOOGLE_CLIENT_ID: {{ $.Values.googleOauthClientId | b64enc }}
  GF_AUTH_GOOGLE_CLIENT_SECRET: {{ $.Values.googleOauthClientSecret | b64enc }}