apiVersion: v1
kind: Secret
metadata:
  name: gsp-harbor-notary-tls
  namespace: gsp-system
data:
  # docs say the keys should be like this:
  tls.ca: {{ .Values.harbor.notary.tlsCA | b64enc }}
  tls.crt: {{ .Values.harbor.notary.tlsCert | b64enc }}
  tls.key: {{ .Values.harbor.notary.tlsKey | b64enc }}
  # ...but in v1.1.1 of the chart it really expects the keys like this:
  ca: {{ .Values.harbor.notary.tlsCA | b64enc }}
  crt: {{ .Values.harbor.notary.tlsCert | b64enc }}
  key: {{ .Values.harbor.notary.tlsKey | b64enc }}
