apiVersion: v1
kind: Secret
metadata:
  name: gsp-harbor-notary-tls
  namespace: gsp-system
data:
  tls.ca: {{ .Values.harbor.notary.tlsCA }}
  tls.crt: {{ .Values.harbor.notary.tlsCert }}
  tls.key: {{ .Values.harbor.notary.tlsKey }}
