apiVersion: v1
kind: Secret
metadata:
  name: gsp-harbor-notary-tls
  namespace: gsp-system
data:
  tls.ca: {{ .Values.harbor.notary.tlsCA | b64enc }}
  tls.crt: {{ .Values.harbor.notary.tlsCert | b64enc }}
  tls.key: {{ .Values.harbor.notary.tlsKey | b64enc }}
