apiVersion: v1
kind: Secret
metadata:
  name: gsp-harbor-notary-tls
  namespace: gsp-system
data:
  # docs say the keys should be like this:
  {{ if .Values.harbor.notary.tlsCA }}
    tls.ca: {{ .Values.harbor.notary.tlsCA | b64enc }}
  {{ end }}
  {{ if .Values.harbor.notary.tlsCert }}
    tls.crt: {{ .Values.harbor.notary.tlsCert | b64enc }}
  {{ end }}
  {{ if .Values.harbor.notary.tlsKey }}
    tls.key: {{ .Values.harbor.notary.tlsKey | b64enc }}
  {{ end }}

  # ...but in v1.1.1 of the chart it really expects the keys like this:
  {{ if .Values.harbor.notary.tlsCA }}
    ca: {{ .Values.harbor.notary.tlsCA | b64enc }}
  {{ end }}
  {{ if .Values.harbor.notary.tlsCert }}
    crt: {{ .Values.harbor.notary.tlsCert | b64enc }}
  {{ end }}
  {{ if .Values.harbor.notary.tlsKey }}
    key: {{ .Values.harbor.notary.tlsKey | b64enc }}
  {{ end }}
