apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-letsencrypt-staging
spec:
  acme:
    email: {{ .Values.letsencrypt.email }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Name }}-letsencrypt-staging
    dns01:
      providers:
      - name: gsp
        route53:
          region: eu-west-2
