apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: teams.concourse.k8s.io
spec:
  group: concourse.k8s.io
  names:
    kind: Team
    plural: teams
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            roles:
              items:
                properties:
                  github:
                    properties:
                      teams:
                        items:
                          type: string
                        type: array
                      users:
                        items:
                          type: string
                        type: array
                    type: object
                  local:
                    properties:
                      users:
                        items:
                          type: string
                        type: array
                    type: object
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - roles
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
