apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: pipeline-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipeline-operator-role
subjects:
- kind: ServiceAccount
  name: {{ template "pipelineOperator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
