apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pipeline-operator-role
rules:
- apiGroups:
  - concourse.k8s.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - concourse.k8s.io
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - concourse.k8s.io
  resources:
  - teams/status
  verbs:
  - get
  - update
  - patch
