---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pipeline-operator
  labels:
    app.kubernetes.io/name: "pipeline-operator"
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    control-plane: concourse-operator
    controller-tools.k8s.io: "1.0"
data:
  concourse_password: {{ .Values.pipelineOperator.concoursePassword | b64enc }}
