dependencies:
  - name: "fluentd-cloudwatch"
    version: 0.6.4
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "concourse"
    version: 8.2.5
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kiam"
    version: 2.5.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "harbor"
    version: 1.1.3
    repository: https://helm.goharbor.io/
