dependencies:
  - name: "prometheus-operator"
    version: 5.0.11
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "fluentd-cloudwatch"
    version: 0.6.4
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
    condition: global.runningOnAws
  - name: "concourse"
    version: 5.0.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: "kiam"
    version: 2.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: global.runningOnAws
  - name: external-dns
    version: 1.7.3
    repository: https://kubernetes-charts.storage.googleapis.com/
