global:
  account:
    name: "local"
  cluster:
    domain: "local.govsandbox.uk"

concourse:
  worker:
    persistence:
      enabled: false
    replicas: 1
  postgresql:
    persistence:
      enabled: false
