global:
  account:
    name: "local"
  cluster:
    domain: "local.govsandbox.uk"

concourse:
  concourse:
    web:
      externalUrl: "http://ci.local.govsandbox.uk"
  worker:
    persistence:
      enabled: false
    replicas: 1
  postgresql:
    persistence:
      enabled: false
