apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "gsp-canary.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "gsp-canary.fullname" . }}-ingress-certificate
  dnsNames:
  - "canary.{{ .Values.global.cluster.domain }}"
  issuerRef:
    name: letsencrypt-r53
    kind: ClusterIssuer
