{{ if .Values.gatekeeper.enabled }}
---
apiVersion: config.gatekeeper.sh/v1alpha1
kind: Config
metadata:
  name: config
  namespace: {{ .Release.Namespace }}
spec:
  sync:
    syncOnly:
      - group: ""
        version: "v1"
        kind: "Pod"
{{ end }}
