---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: admin
  name: {{ .Values.global.cluster.name }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: Group
  name: {{ .Values.global.cluster.name }}-admin
  apiGroup: rbac.authorization.k8s.io
