apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
  {{- range .Values.bootstrapRoleARNs }}
    - rolearn: {{ . | quote }}
      username: system:node:{{ "{{" }}EC2PrivateDNSName{{ "}}" }}
      groups:
        - system:bootstrappers
        - system:nodes
  {{- end }}
  {{- range .Values.adminRoleARNs }}
    - rolearn: {{ . | quote }}
      username: admin:{{ "{{" }}SessionName{{ "}}" }}
      groups:
        - system:masters
  {{- end }}
  {{- range .Values.sreRoleARNs }}
    - rolearn: {{ . | quote }}
      username: sre
      groups:
        - sre
  {{- end }}
  {{- range .Values.users }}
    - rolearn: {{ .roleARN | quote }}
      username: {{ .name }}
      groups:
      {{- range .roles }}
        - {{ . }}
      {{- end }}
  {{- end }}
  mapUsers: |
  {{- range .Values.adminUserARNs }}
    - userarn: {{ . | quote }}
      username: admin
      groups:
        - system:masters
  {{- end }}
  {{- range .Values.sreUserARNs }}
    - userarn: {{ . | quote }}
      username: sre
      groups:
        - sre
  {{- end }}
