---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    namespace: istio-system
    istio-injection: disabled
  annotations:
    iam.amazonaws.com/permitted: {{ .Values.istioSystem.permittedRolesRegex | quote }}
