---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    namespace: istio-system
    istio-injection: disabled
    istio: system
  annotations:
    iam.amazonaws.com/permitted: {{ .Values.istioSystemRoleRegex | quote }}
