{{- range .Values.namespaces }}
{{- $defaultedPermittedRolesRegex := .permittedRolesRegex | default "^$" }}
{{- $permittedRolesRegex := printf "%s|^svcop-%s-%s-.*$|^%s$" $defaultedPermittedRolesRegex $.Values.global.cluster.name .name $.Values.externalDns.iamRoleName }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .name }}
  labels:
    namespace: {{ .name }}
{{- if .talksToHsm }}
    talksToHsm: "true"
{{- end }}
  annotations:
    iam.amazonaws.com/permitted: {{ $permittedRolesRegex | quote }}
{{- end }}
