apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: sre
  name: sre
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
    - delete
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs:
    - create
  - apiGroups: [""]
    resources: ["nodes"]
    verbs:
    - get
    - watch
    - list
  - apiGroup: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs:
    - get
    - watch
    - list
  - apiGroup: ["apiextensions.k8s.io"]
    resources: ["*"]
    verbs:
    - get
    - watch
    - list
  - apiGroups: ["config.istio.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["authentication.istio.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["rbac.istio.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
  - apiGroups: ["monitoring.kiali.io"]
    resources: ["*"]
    verbs:
    - get
    - list
    - watch

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: sre
  name: {{ .Values.global.cluster.name }}-sre
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sre
subjects:
- kind: Group
  name: {{ .Values.global.cluster.name }}-sre
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: sre
  name: {{ .Values.global.cluster.name }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  name: {{ .Values.global.cluster.name }}-sre
  apiGroup: rbac.authorization.k8s.io
