apiVersion: concourse.k8s.io/v1beta1
kind: Pipeline
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: pipeline-sample
spec:
  pipelineString: |
    resources:
    - name: bad
      type: bad-not-exist
    jobs:
    - name: hello-world
      plan:
      - task: hello-world
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: busybox}
          run:
            path: echo
            args:
            - hello world

