apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pipelineOperator.serviceAccountName" . }}
  labels:
    app: "pipeline-operator"
    chart: {{ .Chart.Name }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
