---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Release.Name }}-sealed-secrets-key
data:
  tls.crt: {{ .Values.secrets.public_certificate | quote }}
  tls.key: {{ .Values.secrets.private_key | quote }}
