{{ if .Values.global.runningOnAws }}
{{- $ca := genCA "Kiam CA" 365 }}
{{- $serverCert := genSignedCert (printf "%s-kiam-server" .Release.Name) (list "127.0.0.1") (list "127.0.0.1:443" "127.0.0.1:9610" (printf "%s-kiam-server" .Release.Name) (printf "%s-kiam-server:443" .Release.Name)) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "kiam-server-tls"
data:
  server.pem: {{ $serverCert.Cert | b64enc | quote }}
  server-key.pem: {{ $serverCert.Key | b64enc | quote }}
  ca.pem: {{ $ca.Cert | b64enc | quote }}

---

{{- $agentCert := genSignedCert "Kiam Agent" nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: "kiam-agent-tls"
data:
  agent.pem: {{ $agentCert.Cert | b64enc | quote }}
  agent-key.pem: {{ $agentCert.Key | b64enc | quote }}
  ca.pem: {{ $ca.Cert | b64enc | quote }}

---
{{ end }}
